// Word-by-word PT->EN substitution tuned to the exact vocabulary used in
// data/exercises.json, so the bulk "link English examples" tool in the
// Exercise Manager has a reasonable query to search the media provider
// with. It is intentionally approximate — the admin still reviews the
// linked thumbnails afterward and can fix stragglers by hand.
const WORD_MAP: Record<string, string> = {
  abdominal: 'crunch',
  abducao: 'abduction',
  abdutora: 'abductor',
  afundo: 'lunge',
  agachamento: 'squat',
  alta: 'high',
  alternada: 'alternating',
  alto: 'high',
  aberta: 'wide grip',
  arnold: 'arnold',
  articulado: 'machine',
  baixa: 'low',
  baixo: 'low',
  banco: 'bench',
  barra: 'barbell',
  bicicleta: 'bicycle',
  biceps: 'biceps',
  bulgaro: 'bulgarian',
  burrinho: 'donkey',
  busto: 'chest',
  cabo: 'cable',
  cadeira: 'seated',
  caminhada: 'walk',
  canivete: 'v-up',
  cavalinho: 't-bar',
  chest: 'chest',
  chin: 'chin-up',
  coice: 'kickback',
  com: 'with',
  concentrada: 'concentration',
  corda: 'rope',
  corrida: 'running',
  costas: 'back',
  crossover: 'crossover',
  crucifixo: 'fly',
  curvada: 'bent-over',
  de: '',
  declinada: 'decline',
  declinado: 'decline',
  deitado: 'lying',
  desenvolvimento: 'shoulder press',
  diamante: 'diamond',
  direta: 'straight bar',
  encolhimento: 'shrug',
  elastico: 'band',
  elevacao: 'raise',
  eliptico: 'elliptical',
  em: '',
  ergometro: 'rowing machine',
  escada: 'stairmaster',
  esteira: 'treadmill',
  extensao: 'extension',
  extensora: 'leg extension',
  face: 'face',
  farmer: "farmer's walk",
  fechada: 'close grip',
  fechado: 'close grip',
  flexao: 'push-up',
  flexora: 'leg curl',
  frente: 'front',
  frontal: 'front',
  gluteo: 'glute',
  goblet: 'goblet',
  good: 'good morning',
  guilhotina: 'guillotine',
  guiada: 'guided',
  hack: 'hack squat',
  halter: 'dumbbell',
  halteres: 'dumbbell',
  hip: 'hip thrust',
  hiperextensao: 'hyperextension',
  inclinada: 'incline',
  inclinado: 'incline',
  infra: 'lower abs',
  invertida: 'reverse',
  invertido: 'reverse',
  joelhos: 'knee',
  jumping: 'jumping jack',
  kickback: 'kickback',
  lateral: 'lateral',
  leg: 'leg',
  levantamento: 'deadlift',
  livre: 'free',
  lombar: 'lower back',
  machine: 'machine',
  maquina: 'machine',
  martelo: 'hammer',
  mergulho: 'dip',
  mesa: 'table',
  militar: 'military',
  na: '',
  natacao: 'swimming',
  neutra: 'neutral grip',
  no: '',
  oblíquo: 'oblique',
  oblique: 'oblique',
  overhead: 'overhead',
  panturrilha: 'calf raise',
  paralelas: 'parallel bars',
  passada: 'lunge',
  pegada: 'grip',
  peck: 'pec deck',
  peito: 'chest',
  pelvica: 'hip thrust',
  perna: 'leg',
  pernas: 'legs',
  polia: 'cable',
  ponte: 'bridge',
  prancha: 'plank',
  pull: 'pull',
  pulldown: 'pulldown',
  pulley: 'pulley',
  pullover: 'pullover',
  pulo: 'jump',
  pular: 'jump rope',
  punho: 'wrist',
  puxada: 'pulldown',
  quadril: 'hip',
  reto: 'flat',
  rotacao: 'rotation',
  rotador: 'rotator cuff',
  romeno: 'romanian',
  roda: 'wheel',
  rosca: 'curl',
  russian: 'russian twist',
  scotch: 'preacher',
  scott: 'preacher',
  sentada: 'seated',
  sentado: 'seated',
  serrote: 'single-arm row',
  sissy: 'sissy squat',
  sit: 'sit-up',
  smith: 'smith machine',
  step: 'step up',
  stiff: 'stiff-leg deadlift',
  subida: 'step up',
  sumo: 'sumo',
  superman: 'superman',
  supinada: 'underhand grip',
  supino: 'bench press',
  supra: 'upper abs',
  terra: 'deadlift',
  testa: 'skull crusher',
  tiros: 'sprints',
  triangulo: 'triangle',
  triceps: 'triceps',
  tronco: 'torso',
  twist: 'twist',
  unilateral: 'single-arm',
  up: 'up',
  v: 'v-bar',
  walk: 'walk',
  wood: 'wood chop',
  y: 'y-raise',
};

function normalizeWord(word: string): string {
  return word.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
}

/** Best-effort PT->EN translation of a catalog exercise name for searching the media provider. Drops parenthetical hints (already English) and translates the remaining words one by one. */
export function translateExerciseNameToEnglish(name: string): string {
  const withoutParens = name.replace(/\([^)]*\)/g, ' ');
  const words = withoutParens
    .split(/\s+/)
    .map((word) => word.replace(/[^\p{L}-]/gu, ''))
    .filter(Boolean);
  const translated = words
    .map((word) => {
      const key = normalizeWord(word);
      return key in WORD_MAP ? WORD_MAP[key] : word;
    })
    .filter((word): word is string => Boolean(word && word.trim()));
  const result = translated.join(' ').replace(/\s+/g, ' ').trim();
  return result || name;
}
